/*
 * This file was generated by the Gradle "init" task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

plugins {
  id("org.jetbrains.kotlin.jvm") version "1.3.61"
  application
  jacoco
  id("org.sonarqube") version "2.8"
}

group = "io.code.morning"
version = "0.0.1-SNAPSHOT"

java {
  sourceCompatibility = JavaVersion.VERSION_11
  targetCompatibility = JavaVersion.VERSION_11
}

repositories {
  jcenter()
}

dependencies {
  // Align versions of all Kotlin components
  implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

  // Use the Kotlin JDK 8 standard library.
  implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

  // Lambda
  implementation("com.amazonaws:aws-java-sdk-lambda:1.11.745")
  implementation("com.amazonaws:aws-lambda-java-core:1.2.0")

  // Testing
  testImplementation("org.jetbrains.kotlin:kotlin-test")
  testImplementation("org.jetbrains.kotlin:kotlin-test-junit")
  testImplementation("org.junit.jupiter:junit-jupiter-api:5.6.0")
  testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.6.0")
}

application {
  // Define the main class for the application.
  mainClassName = "io.code.morning.AwsBillingNotificationKt"
}

tasks.withType<Test> {
  useJUnitPlatform()
}

jacoco {
  toolVersion = "0.8.5"
  reportsDir = file("$buildDir/reports/jacoco")
}

tasks.jacocoTestReport {
  reports {
    xml.isEnabled = true
    html.isEnabled = false
  }

  dependsOn(tasks.withType<Test>())
}

sonarqube {
  properties {
    property("sonar.sourceEncoding", "UTF-8")
    property("sonar.projectKey", "api")
    property("sonar.coverage.jacoco.xmlReportPaths", "build/reports/jacoco/test/jacocoTestReport.xml")
  }
}

