# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.15

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle.kts" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: gradle dependencies
      - run: gradle test jacocoTestReport && /bin/bash .circleci/sonarqube.sh
      - run: gradle build

      - aws-s3/copy:
          from: build/libs/aws-billing-notification-0.0.1-SNAPSHOT.jar
          to: 's3://morning-code-aws-billing-notification'

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle.kts" }}


